locale: "en"
title: "MALer Lab"
email: "dasaemj@sogang.ac.kr"
description: "Music and Art Learning Lab, Sogang University, South Korea"
theme: minima
name: "MALer Lab"
domain: MALerLab.github.io
url: "https://MALerLab.github.io"
baseurl: ""
atom_path: "atom.xml"

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/

plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag

scholar:
  style: apa
  locale: en
  source: "./_bibliography"
  bibliography: "references.bib"
  # bibliography_template: "%{reference}"
  # details_dir: "publications"
  # details_layout: "publication"

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive

seo:
  title: "MALer Lab"
  description: "Music and Art Learning Lab, Sogang University, South Korea"
  image: "https://MALerLab.github.io/assets/images/maler_og.png"
  url: "https://MALerLab.github.io"
  twitter:
    username: "MALerLab"
    card: "summary_large_image"

author:
  name: "MALer Lab"
  url: "https://MALerLab.github.io"
  github: "MALerLab"
  email: "dasaemj@sogang.ac.kr"

defaults:
  - scope:
      path: ""
      type: ""
    values:
      image: "/assets/images/maler-assets/maler_og.png"
